name: .NET

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/src/Fitweb.API
    - name: Build
      run: dotnet build --configuration Release Backend/src/Fitweb.API
    - name: Application tests
      run: dotnet test --configuration Release Backend/tests/Fitweb.Application.UnitTests
    - name: Domain tests
      run: dotnet test --configuration Release Backend/tests/Fitweb.Domain.UnitTests
    - name: Infrastructure identity tests
      run: dotnet test --configuration Release Backend/tests/Fitweb.Infrastructure.Identity.UnitTests
